/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokofurniture;

import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class Administrator extends javax.swing.JFrame {    
    CardLayout cardLayout;
    private DrawTable administrator = new DrawTable();
    private String path = null;
    private FileInputStream fimage = null;
    private File selectedImage;
    ConnectionClass adminLogin = new ConnectionClass();
    
    
    public Administrator() {
        initComponents();
        System.out.println(adminLogin.isLogin);
        administrator.showDataToTableAdmin(tableAdmin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAdminDashboard = new javax.swing.JPanel();
        panelAdminDashboardLabel = new javax.swing.JLabel();
        labelNamaBarang = new javax.swing.JLabel();
        labelHargaBarang = new javax.swing.JLabel();
        labelStok = new javax.swing.JLabel();
        namaBarangTextField = new javax.swing.JTextField();
        hargaBarangTextField = new javax.swing.JTextField();
        editButtin = new javax.swing.JButton();
        tambahButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        labelDeskripsi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deskripsiTextArea = new javax.swing.JTextArea();
        clearButton1 = new javax.swing.JButton();
        panelAddImage = new javax.swing.JPanel();
        labelAddImage = new javax.swing.JLabel();
        stokTextField1 = new javax.swing.JTextField();
        scrollPanelAdmin = new javax.swing.JScrollPane();
        tableAdmin = new javax.swing.JTable();
        logoutButton = new javax.swing.JButton();
        buttonTambahGambar = new javax.swing.JButton();
        labelIdBarang = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelAdminDashboard.setBackground(new java.awt.Color(176, 187, 205));

        panelAdminDashboardLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        panelAdminDashboardLabel.setForeground(new java.awt.Color(237, 246, 255));
        panelAdminDashboardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelAdminDashboardLabel.setText("ADMIN DASHBOARD");

        labelNamaBarang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNamaBarang.setText("NAMA BARANG");

        labelHargaBarang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelHargaBarang.setText("HARGA BARANG");

        labelStok.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelStok.setText("STOK");

        editButtin.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        editButtin.setText("EDIT");
        editButtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtinActionPerformed(evt);
            }
        });

        tambahButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tambahButton.setText("TAMBAH");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        hapusButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hapusButton.setText("HAPUS");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        labelDeskripsi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDeskripsi.setText("DESKRIPSI BARANG");

        deskripsiTextArea.setColumns(20);
        deskripsiTextArea.setRows(5);
        jScrollPane1.setViewportView(deskripsiTextArea);

        clearButton1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        clearButton1.setText("CLEAR");
        clearButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton1ActionPerformed(evt);
            }
        });

        labelAddImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAddImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addimage.png"))); // NOI18N

        javax.swing.GroupLayout panelAddImageLayout = new javax.swing.GroupLayout(panelAddImage);
        panelAddImage.setLayout(panelAddImageLayout);
        panelAddImageLayout.setHorizontalGroup(
            panelAddImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAddImage, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        panelAddImageLayout.setVerticalGroup(
            panelAddImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAddImage, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        scrollPanelAdmin.setToolTipText("");

        tableAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID BARANG", "NAMA BARANG", "HARGA BARANG", "STOK", "DESKRIPSI", "GAMBAR"
            }
        ));
        tableAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAdminMouseClicked(evt);
            }
        });
        scrollPanelAdmin.setViewportView(tableAdmin);

        logoutButton.setText("LOGOUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        buttonTambahGambar.setText("TAMBAH GAMBAR");
        buttonTambahGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahGambarActionPerformed(evt);
            }
        });

        labelIdBarang.setText("0");

        javax.swing.GroupLayout panelAdminDashboardLayout = new javax.swing.GroupLayout(panelAdminDashboard);
        panelAdminDashboard.setLayout(panelAdminDashboardLayout);
        panelAdminDashboardLayout.setHorizontalGroup(
            panelAdminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminDashboardLayout.createSequentialGroup()
                .addGroup(panelAdminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdminDashboardLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(panelAdminDashboardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAdminDashboardLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelAdminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNamaBarang)
                            .addComponent(labelHargaBarang)
                            .addComponent(labelStok)
                            .addComponent(labelDeskripsi))
                        .addGap(7, 7, 7)
                        .addGroup(panelAdminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaBarangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaBarangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stokTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(labelIdBarang)
                        .addGap(124, 124, 124)
                        .addGroup(panelAdminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelAddImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonTambahGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelAdminDashboardLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(tambahButton)
                        .addGap(19, 19, 19)
                        .addComponent(editButtin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(clearButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(393, Short.MAX_VALUE))
            .addComponent(scrollPanelAdmin)
        );
        panelAdminDashboardLayout.setVerticalGroup(
            panelAdminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminDashboardLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(panelAdminDashboardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(panelAdminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdminDashboardLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelNamaBarang)
                        .addGap(24, 24, 24)
                        .addComponent(labelHargaBarang)
                        .addGap(24, 24, 24)
                        .addComponent(labelStok)
                        .addGap(24, 24, 24)
                        .addComponent(labelDeskripsi))
                    .addGroup(panelAdminDashboardLayout.createSequentialGroup()
                        .addComponent(namaBarangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(hargaBarangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(stokTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAdminDashboardLayout.createSequentialGroup()
                        .addComponent(panelAddImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(buttonTambahGambar)))
                .addGap(10, 10, 10)
                .addComponent(scrollPanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(panelAdminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambahButton)
                    .addComponent(editButtin)
                    .addComponent(hapusButton)
                    .addComponent(clearButton1)
                    .addComponent(logoutButton))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAdminDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAdminDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
    
    
    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        adminLogin.isLogin = false;
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed
    
    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        // TODO add your handling code here:
        
        if (namaBarangTextField.getText().isEmpty()  || 
            hargaBarangTextField.getText().isEmpty() || 
            stokTextField1.getText().isEmpty() || 
            deskripsiTextArea.getText().isEmpty() || fimage == null) 
        {
            JOptionPane.showMessageDialog(this, "Semua data harus terisi!!!");
        } else{
            TokoFurnitureDB.insertIntoDatabase(
                   namaBarangTextField.getText(), 
                   Integer.valueOf(hargaBarangTextField.getText()), 
                   Integer.valueOf(stokTextField1.getText()), 
                   deskripsiTextArea.getText(), 
                   fimage
            );

            administrator.showDataToTableAdmin(tableAdmin);
            namaBarangTextField.setText("");
            hargaBarangTextField.setText("");
            stokTextField1.setText("");
            deskripsiTextArea.setText("");       
        }
    }//GEN-LAST:event_tambahButtonActionPerformed
    
    private void buttonTambahGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahGambarActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        selectedImage = fc.getSelectedFile(); 
        
        if (selectedImage != null) {
            path = selectedImage.getAbsolutePath();
            
            ImageIcon image = new ImageIcon(
                new ImageIcon(path).getImage().getScaledInstance(labelAddImage.getWidth(), 
                labelAddImage.getHeight(), Image.SCALE_SMOOTH)
            );
            
            labelAddImage.setIcon(image);
            
            try {
                File imageicon = new File(path);
                fimage = new FileInputStream(imageicon);          
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
          
        } else{
            JOptionPane.showMessageDialog(null, "Wajib memasukkan gambar!!");
            fc.showOpenDialog(this);
            selectedImage = fc.getSelectedFile();
            
            path = selectedImage.getAbsolutePath();
            
            ImageIcon image = new ImageIcon(
                new ImageIcon(path).getImage().getScaledInstance(labelAddImage.getWidth(), 
                labelAddImage.getHeight(), Image.SCALE_SMOOTH)
            );
            
            labelAddImage.setIcon(image);
            
            try {
            
            System.out.println(path);
                File imageicon = new File(path);
                fimage = new FileInputStream(imageicon);          
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        
    }//GEN-LAST:event_buttonTambahGambarActionPerformed

    private void tableAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAdminMouseClicked
        // TODO add your handling code here:
        
        // buat objek baru
        administrator = new DrawTable(
                tableAdmin, 
                labelIdBarang, 
                namaBarangTextField,
                hargaBarangTextField, 
                stokTextField1, 
                deskripsiTextArea
        );
        
        administrator.tableClickedAdmin();
        
        int i = tableAdmin.getSelectedRow();
        if(tableAdmin.getValueAt(i, 5) != null) {
            ImageIcon image1 = (ImageIcon)tableAdmin.getValueAt(i, 5);
            Image image2 = image1.getImage().getScaledInstance(labelAddImage.getWidth(), 
                           labelAddImage.getHeight(), Image.SCALE_SMOOTH);
            
            ImageIcon image3 = new ImageIcon(image2);
            labelAddImage.setIcon(image3);

        } else{
            labelAddImage.setText("No Image!!");
        }
    }//GEN-LAST:event_tableAdminMouseClicked

    private void clearButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_clearButton1ActionPerformed

    private void editButtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtinActionPerformed
        // TODO add your handling code here:
        TokoFurnitureDB.updateToDatabase(
            Integer.valueOf(labelIdBarang.getText()),
            namaBarangTextField.getText(), 
            Integer.valueOf(hargaBarangTextField.getText()), 
            Integer.valueOf(stokTextField1.getText()),
            deskripsiTextArea.getText(), fimage
        );
        administrator.showDataToTableAdmin(tableAdmin);
        
        namaBarangTextField.setText("");
        hargaBarangTextField.setText("");
        stokTextField1.setText("");
        deskripsiTextArea.setText("");
    }//GEN-LAST:event_editButtinActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        // TODO add your handling code here:
        TokoFurnitureDB.deleteFromDatabase(
            Integer.valueOf(labelIdBarang.getText())
        );
        administrator.showDataToTableAdmin(tableAdmin);
        
        namaBarangTextField.setText("");
        hargaBarangTextField.setText("");
        stokTextField1.setText("");
        deskripsiTextArea.setText("");
    }//GEN-LAST:event_hapusButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrator().setVisible(true);
            }
        });
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonTambahGambar;
    private javax.swing.JButton clearButton1;
    private javax.swing.JTextArea deskripsiTextArea;
    private javax.swing.JButton editButtin;
    private javax.swing.JButton hapusButton;
    private javax.swing.JTextField hargaBarangTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAddImage;
    private javax.swing.JLabel labelDeskripsi;
    private javax.swing.JLabel labelHargaBarang;
    private javax.swing.JLabel labelIdBarang;
    private javax.swing.JLabel labelNamaBarang;
    private javax.swing.JLabel labelStok;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField namaBarangTextField;
    private javax.swing.JPanel panelAddImage;
    private javax.swing.JPanel panelAdminDashboard;
    private javax.swing.JLabel panelAdminDashboardLabel;
    private javax.swing.JScrollPane scrollPanelAdmin;
    private javax.swing.JTextField stokTextField1;
    private javax.swing.JTable tableAdmin;
    private javax.swing.JButton tambahButton;
    // End of variables declaration//GEN-END:variables

}