/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokofurniture;

import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.JOptionPane;

public class Home extends javax.swing.JFrame {
    private CardLayout cardLayout;
    private DrawTable homepageTable = new DrawTable();
    protected boolean isLogin = false;
    private ConnectionClass login = new ConnectionClass(isLogin);
    
    public Home() {
        initComponents();
        System.out.println(login.isLogin);
        homepageTable.showDataToTableHome(tableHome);
        cardLayout = (CardLayout) (panelCard.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCard = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        scrollHome = new javax.swing.JScrollPane();
        tableHome = new javax.swing.JTable();
        labelPhotoHome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaDeskripsi = new javax.swing.JTextArea();
        panelLoginAdmin = new javax.swing.JPanel();
        panelAdminLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passTextField = new javax.swing.JPasswordField();
        buttonLogin = new javax.swing.JButton();
        passLogoLabel = new javax.swing.JLabel();
        usernameLogoLabel1 = new javax.swing.JLabel();
        panelContact = new javax.swing.JPanel();
        panelContactLabel = new javax.swing.JLabel();
        panelContactWhatsappLogo = new javax.swing.JLabel();
        panelContactWhatsappNo = new javax.swing.JLabel();
        panelContactLabel1 = new javax.swing.JLabel();
        panelAbout = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        buttonHome = new javax.swing.JButton();
        buttonAdmin = new javax.swing.JButton();
        buttonContact = new javax.swing.JButton();
        buttonAbout = new javax.swing.JButton();
        panelLogo = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        buttonPemesanan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelCard.setBackground(new java.awt.Color(255, 255, 255));
        panelCard.setLayout(new java.awt.CardLayout());

        panelHome.setBackground(new java.awt.Color(176, 187, 205));

        scrollHome.setBackground(new java.awt.Color(176, 187, 205));
        scrollHome.setForeground(new java.awt.Color(176, 187, 205));
        scrollHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrollHomeMouseClicked(evt);
            }
        });

        tableHome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NAMA BARANG", "HARGA BARANG", "STOK", "DESKRIPSI", "GAMBAR"
            }
        ));
        tableHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHomeMouseClicked(evt);
            }
        });
        scrollHome.setViewportView(tableHome);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("GAMBAR BARANG");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("DESKRIPSI BARANG");

        textAreaDeskripsi.setColumns(20);
        textAreaDeskripsi.setRows(5);
        jScrollPane2.setViewportView(textAreaDeskripsi);

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(labelPhotoHome, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addComponent(scrollHome, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPhotoHome, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        panelCard.add(panelHome, "panelHome");

        panelLoginAdmin.setBackground(new java.awt.Color(176, 187, 205));
        panelLoginAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAdminLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        panelAdminLabel.setForeground(new java.awt.Color(237, 246, 255));
        panelAdminLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelAdminLabel.setText("LOGIN ADMIN");
        panelLoginAdmin.add(panelAdminLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 235, 39));

        usernameTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        usernameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usernameTextField.setText("Username");
        usernameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 111, 180)));
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        panelLoginAdmin.add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 295, 35));

        passTextField.setText("Password");
        passTextField.setActionCommand("<Not Set>");
        passTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 111, 180)));
        passTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        panelLoginAdmin.add(passTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 163, 295, 34));

        buttonLogin.setBackground(new java.awt.Color(40, 111, 180));
        buttonLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(237, 246, 255));
        buttonLogin.setText("LOGIN");
        buttonLogin.setBorder(null);
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        panelLoginAdmin.add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 235, 294, 40));

        passLogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_password_30px.png"))); // NOI18N
        panelLoginAdmin.add(passLogoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 163, 48, 35));

        usernameLogoLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLogoLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_user_30px.png"))); // NOI18N
        panelLoginAdmin.add(usernameLogoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 100, 48, 35));

        panelCard.add(panelLoginAdmin, "panelLoginAdmin");

        panelContact.setBackground(new java.awt.Color(176, 187, 205));

        panelContactLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        panelContactLabel.setForeground(new java.awt.Color(237, 246, 255));
        panelContactLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelContactLabel.setText("HUBUNGI KAMI KE NOMOR WHATSAPP");

        panelContactWhatsappLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelContactWhatsappLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_whatsapp_50px.png"))); // NOI18N

        panelContactWhatsappNo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        panelContactWhatsappNo.setForeground(new java.awt.Color(237, 246, 255));
        panelContactWhatsappNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelContactWhatsappNo.setText("0854-2212-9910");

        panelContactLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        panelContactLabel1.setForeground(new java.awt.Color(237, 246, 255));
        panelContactLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelContactLabel1.setText("DI BAWAH INI");

        javax.swing.GroupLayout panelContactLayout = new javax.swing.GroupLayout(panelContact);
        panelContact.setLayout(panelContactLayout);
        panelContactLayout.setHorizontalGroup(
            panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContactLayout.createSequentialGroup()
                .addGroup(panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelContactLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContactLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panelContactLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(panelContactWhatsappLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContactWhatsappNo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );
        panelContactLayout.setVerticalGroup(
            panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContactLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContactLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelContactWhatsappLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContactWhatsappNo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(398, Short.MAX_VALUE))
        );

        panelCard.add(panelContact, "panelContact");

        panelAbout.setBackground(new java.awt.Color(176, 187, 205));

        javax.swing.GroupLayout panelAboutLayout = new javax.swing.GroupLayout(panelAbout);
        panelAbout.setLayout(panelAboutLayout);
        panelAboutLayout.setHorizontalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
        );
        panelAboutLayout.setVerticalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        panelCard.add(panelAbout, "panelAbout");

        sidePanel.setBackground(new java.awt.Color(40, 111, 180));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonHome.setBackground(new java.awt.Color(176, 187, 205));
        buttonHome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonHome.setForeground(new java.awt.Color(40, 111, 180));
        buttonHome.setText("HOME");
        buttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHomeActionPerformed(evt);
            }
        });
        sidePanel.add(buttonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, 40));

        buttonAdmin.setBackground(new java.awt.Color(176, 187, 205));
        buttonAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonAdmin.setForeground(new java.awt.Color(40, 111, 180));
        buttonAdmin.setText("ADMIN");
        buttonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdminActionPerformed(evt);
            }
        });
        sidePanel.add(buttonAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 40));

        buttonContact.setBackground(new java.awt.Color(176, 187, 205));
        buttonContact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonContact.setForeground(new java.awt.Color(40, 111, 180));
        buttonContact.setText("CONTACT");
        buttonContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContactActionPerformed(evt);
            }
        });
        sidePanel.add(buttonContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 150, 40));

        buttonAbout.setBackground(new java.awt.Color(176, 187, 205));
        buttonAbout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonAbout.setForeground(new java.awt.Color(40, 111, 180));
        buttonAbout.setText("ABOUT");
        buttonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAboutActionPerformed(evt);
            }
        });
        sidePanel.add(buttonAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 150, 40));

        panelLogo.setBackground(new java.awt.Color(40, 111, 180));

        labelLogo.setBackground(new java.awt.Color(40, 111, 180));
        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TF.png"))); // NOI18N

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(panelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 80));

        buttonPemesanan.setBackground(new java.awt.Color(176, 187, 205));
        buttonPemesanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonPemesanan.setForeground(new java.awt.Color(40, 111, 180));
        buttonPemesanan.setText("PEMESANAN");
        buttonPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPemesananActionPerformed(evt);
            }
        });
        sidePanel.add(buttonPemesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCard.getAccessibleContext().setAccessibleName("");
        panelCard.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    private void buttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHomeActionPerformed
        // TODO add your handling code here:
        homepageTable.showDataToTableHome(tableHome);
        cardLayout.show(panelCard, "panelHome");
    }//GEN-LAST:event_buttonHomeActionPerformed

    private void buttonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdminActionPerformed
        // TODO add your handling code here:
        if(login.isLogin){
           new Administrator().setVisible(true);
        }
        cardLayout.show(panelCard, "panelLoginAdmin");
    }//GEN-LAST:event_buttonAdminActionPerformed

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
        
        if (TokoFurnitureDB.loginAdmin(usernameTextField.getText(), passTextField.getText())) {
            login.isLogin = true;
            JOptionPane.showMessageDialog(null, "Berhasil login!!");
            new Administrator().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Login gagal periksa kembali username dan password");
        }
        
        usernameTextField.setText("");
        passTextField.setText("");
       
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void buttonContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContactActionPerformed
        // TODO add your handling code here:
        new Contact().setVisible(true);
    }//GEN-LAST:event_buttonContactActionPerformed

    private void tableHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHomeMouseClicked
        // TODO add your handling code here:  
        homepageTable = new DrawTable(tableHome);
        homepageTable.setDeskripsiTextArea(textAreaDeskripsi);
        homepageTable.setLabelContaier(labelPhotoHome);
        homepageTable.tableClickedHome();
    }//GEN-LAST:event_tableHomeMouseClicked
    
    private void buttonAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAboutActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelCard, "panelAbout");
    }//GEN-LAST:event_buttonAboutActionPerformed

    private void scrollHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrollHomeMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_scrollHomeMouseClicked

    private void buttonPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPemesananActionPerformed
        // TODO add your handling code here:
        new Pemesanan().setVisible(true);
    }//GEN-LAST:event_buttonPemesananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAbout;
    private javax.swing.JButton buttonAdmin;
    private javax.swing.JButton buttonContact;
    private javax.swing.JButton buttonHome;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonPemesanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelPhotoHome;
    private javax.swing.JPanel panelAbout;
    private javax.swing.JLabel panelAdminLabel;
    private javax.swing.JPanel panelCard;
    private javax.swing.JPanel panelContact;
    private javax.swing.JLabel panelContactLabel;
    private javax.swing.JLabel panelContactLabel1;
    private javax.swing.JLabel panelContactWhatsappLogo;
    private javax.swing.JLabel panelContactWhatsappNo;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLoginAdmin;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JLabel passLogoLabel;
    private javax.swing.JPasswordField passTextField;
    private javax.swing.JScrollPane scrollHome;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable tableHome;
    private javax.swing.JTextArea textAreaDeskripsi;
    private javax.swing.JLabel usernameLogoLabel1;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables

}