/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokofurniture;

import java.awt.CardLayout;




/**
 *
 * @author HP KOMPUTER
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    CardLayout cardLayout;
    
    public Home() {
        initComponents();
        
        buttonHome.setContentAreaFilled(false);
        buttonHome.setBorderPainted(false);
        buttonHome.setOpaque(false);
        
        buttonAdmin.setContentAreaFilled(false);
        buttonAdmin.setBorderPainted(false);
        buttonAdmin.setOpaque(false);
        
        buttonContact.setContentAreaFilled(false);
        buttonContact.setBorderPainted(false);
        buttonContact.setOpaque(false);
        
        buttonAbout.setContentAreaFilled(false);
        buttonAbout.setBorderPainted(false);
        buttonAbout.setOpaque(false);
        
        cardLayout = (CardLayout) (panelCard.getLayout());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCard = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        panelHomeLabel = new javax.swing.JLabel();
        panelAdmin = new javax.swing.JPanel();
        panelAdminLabel = new javax.swing.JLabel();
        panelAbout = new javax.swing.JPanel();
        panelContact = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        btnHome = new javax.swing.JPanel();
        spHome = new javax.swing.JPanel();
        buttonHome = new javax.swing.JButton();
        btnAdmin = new javax.swing.JPanel();
        spAdmin = new javax.swing.JPanel();
        buttonAdmin = new javax.swing.JButton();
        btnContact = new javax.swing.JPanel();
        spContact = new javax.swing.JPanel();
        buttonContact = new javax.swing.JButton();
        btnAbout = new javax.swing.JPanel();
        spAbout = new javax.swing.JPanel();
        buttonAbout = new javax.swing.JButton();
        panelLogo = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelCard.setBackground(new java.awt.Color(255, 255, 255));
        panelCard.setLayout(new java.awt.CardLayout());

        panelHome.setBackground(new java.awt.Color(176, 221, 228));

        panelHomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        panelHomeLabel.setForeground(new java.awt.Color(237, 246, 255));
        panelHomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelHomeLabel.setText("TOKO FURNITURE");

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(panelHomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelHomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(460, Short.MAX_VALUE))
        );

        panelCard.add(panelHome, "panelHome");

        panelAdmin.setBackground(new java.awt.Color(176, 224, 202));

        panelAdminLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        panelAdminLabel.setForeground(new java.awt.Color(237, 246, 255));
        panelAdminLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelAdminLabel.setText("LOGIN ADMIN");

        javax.swing.GroupLayout panelAdminLayout = new javax.swing.GroupLayout(panelAdmin);
        panelAdmin.setLayout(panelAdminLayout);
        panelAdminLayout.setHorizontalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(panelAdminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        panelAdminLayout.setVerticalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAdminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(460, Short.MAX_VALUE))
        );

        panelCard.add(panelAdmin, "panelAdmin");

        panelAbout.setBackground(new java.awt.Color(176, 188, 247));

        javax.swing.GroupLayout panelAboutLayout = new javax.swing.GroupLayout(panelAbout);
        panelAbout.setLayout(panelAboutLayout);
        panelAboutLayout.setHorizontalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        panelAboutLayout.setVerticalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        panelCard.add(panelAbout, "panelAbout");

        panelContact.setBackground(new java.awt.Color(176, 187, 205));

        javax.swing.GroupLayout panelContactLayout = new javax.swing.GroupLayout(panelContact);
        panelContact.setLayout(panelContactLayout);
        panelContactLayout.setHorizontalGroup(
            panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        panelContactLayout.setVerticalGroup(
            panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        panelCard.add(panelContact, "panelContact");

        sidePanel.setBackground(new java.awt.Color(40, 111, 180));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setBackground(new java.awt.Color(34, 79, 141));
        btnHome.setToolTipText("");

        spHome.setBackground(new java.awt.Color(176, 221, 228));
        spHome.setPreferredSize(new java.awt.Dimension(5, 40));
        spHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonHome.setBackground(new java.awt.Color(237, 246, 255));
        buttonHome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonHome.setForeground(new java.awt.Color(237, 246, 255));
        buttonHome.setText("HOME");
        buttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addComponent(spHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 40));

        btnAdmin.setBackground(new java.awt.Color(34, 79, 141));
        btnAdmin.setToolTipText("");

        spAdmin.setBackground(new java.awt.Color(176, 221, 228));
        spAdmin.setPreferredSize(new java.awt.Dimension(5, 40));
        spAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonAdmin.setBackground(new java.awt.Color(237, 246, 255));
        buttonAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonAdmin.setForeground(new java.awt.Color(237, 246, 255));
        buttonAdmin.setText("ADMIN");
        buttonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnAdminLayout = new javax.swing.GroupLayout(btnAdmin);
        btnAdmin.setLayout(btnAdminLayout);
        btnAdminLayout.setHorizontalGroup(
            btnAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAdminLayout.createSequentialGroup()
                .addComponent(spAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        btnAdminLayout.setVerticalGroup(
            btnAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnAdminLayout.createSequentialGroup()
                .addComponent(buttonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidePanel.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 150, 40));

        btnContact.setBackground(new java.awt.Color(34, 79, 141));
        btnContact.setToolTipText("");

        spContact.setBackground(new java.awt.Color(176, 221, 228));
        spContact.setPreferredSize(new java.awt.Dimension(5, 40));
        spContact.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonContact.setBackground(new java.awt.Color(237, 246, 255));
        buttonContact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonContact.setForeground(new java.awt.Color(237, 246, 255));
        buttonContact.setText("CONTACT");
        buttonContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnContactLayout = new javax.swing.GroupLayout(btnContact);
        btnContact.setLayout(btnContactLayout);
        btnContactLayout.setHorizontalGroup(
            btnContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnContactLayout.createSequentialGroup()
                .addComponent(spContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonContact, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnContactLayout.setVerticalGroup(
            btnContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnContactLayout.createSequentialGroup()
                .addComponent(buttonContact, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidePanel.add(btnContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 150, 40));

        btnAbout.setBackground(new java.awt.Color(34, 79, 141));
        btnAbout.setToolTipText("");

        spAbout.setBackground(new java.awt.Color(176, 221, 228));
        spAbout.setPreferredSize(new java.awt.Dimension(5, 40));
        spAbout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonAbout.setBackground(new java.awt.Color(237, 246, 255));
        buttonAbout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonAbout.setForeground(new java.awt.Color(237, 246, 255));
        buttonAbout.setText("ABOUT");
        buttonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnAboutLayout = new javax.swing.GroupLayout(btnAbout);
        btnAbout.setLayout(btnAboutLayout);
        btnAboutLayout.setHorizontalGroup(
            btnAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAboutLayout.createSequentialGroup()
                .addComponent(spAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btnAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnAboutLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(buttonAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );
        btnAboutLayout.setVerticalGroup(
            btnAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btnAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnAboutLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(buttonAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );

        sidePanel.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 40));

        labelLogo.setText("LOGO");

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelLogo)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelLogo)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        sidePanel.add(panelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelCard.getAccessibleContext().setAccessibleName("");
        panelCard.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHomeActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelCard, "panelHome");
    }//GEN-LAST:event_buttonHomeActionPerformed

    private void buttonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdminActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelCard, "panelAdmin");
    }//GEN-LAST:event_buttonAdminActionPerformed

    private void buttonContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContactActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelCard, "panelContact");
    }//GEN-LAST:event_buttonContactActionPerformed

    private void buttonAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAboutActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelCard, "panelAbout");
    }//GEN-LAST:event_buttonAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAbout;
    private javax.swing.JPanel btnAdmin;
    private javax.swing.JPanel btnContact;
    private javax.swing.JPanel btnHome;
    private javax.swing.JButton buttonAbout;
    private javax.swing.JButton buttonAdmin;
    private javax.swing.JButton buttonContact;
    private javax.swing.JButton buttonHome;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JPanel panelAbout;
    private javax.swing.JPanel panelAdmin;
    private javax.swing.JLabel panelAdminLabel;
    private javax.swing.JPanel panelCard;
    private javax.swing.JPanel panelContact;
    private javax.swing.JPanel panelHome;
    private javax.swing.JLabel panelHomeLabel;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel spAbout;
    private javax.swing.JPanel spAdmin;
    private javax.swing.JPanel spContact;
    private javax.swing.JPanel spHome;
    // End of variables declaration//GEN-END:variables

    
}